### ISSUE TITLE
update-publisher-recordsets: MimeNotAllowedError: Mime 'text/html' not allowed in bucket 'datasets'

### ISSUE THREAD

**Issue by roncanepa** [iDigBio/idb-backend#103]
This process could use a better error-handling/escalation method and human review . Here, `http://ip-address:/path/to/resource` results in a normal HTML page and not the dataset.  The system tries to put this into storage and it gets rejected (as it should be) by idb/helpers/media_validation.py.

This could happen if the setup on the provider side changes.  Ideally, these kinds of errors would get surfaced through log notifications and can be corrected by a person so they can be avoided in the future instead of repeated every time the job runs. It would also ideally be caught before actually attempting to put the file.

This might be a good thing to integrate with the collections catalogue.

```
Aug 06 15:15:26 c18node4 idigbio-ingestion[22790]: Harvest File nnnn 'recordset-name-here' @ 'http://ip-address:/path/to/resource'
Aug 06 15:15:26 c18node4 idigbio-ingestion[22790]: Error processing id:nnnn url:http://ip-address:/path/to/resource
                                                   Traceback (most recent call last):
                                                     File "/root/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 470, in harvest_all_file
                                                       harvest_file(r, db)
                                                     File "/root/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 487, in harvest_file
                                                       etag = upload_recordset(r["uuid"], fname, db)
                                                     File "/root/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 505, in upload_recordset
                                                       fobj, url=filereference, type='datasets', owner=config.IDB_UUID)
                                                     File "/root/idb-backend/idb/postgres_backend/db.py", line 701, in fromobj
                                                       mime=mo.mime or mo.detected_mime)
                                                     File "/root/idb-backend/idb/helpers/media_validation.py", line 108, in validate
                                                       return validate_mime_for_type(detected, type)
                                                     File "/root/idb-backend/idb/helpers/media_validation.py", line 82, in validate_mime_for_type
                                                       raise MimeNotAllowedError(mime, t)
                                                   MimeNotAllowedError: Mime 'text/html' not allowed in bucket 'datasets'
```

**Comment by danstoner** [comment]
> This might be a good thing to integrate with the collections catalogue.

The collections catalog was moved to GBIF and does not really relate to datasets (collections and datasets are orthogonal).

I'm not exactly sure what this means: "these kinds of errors would get surfaced through log notifications and can be corrected by a person so they can be avoided in the future..." since the error is in fact in a log and is reviewed by humans.

We do not have log aggregation and monitoring, etc. which would be one way to improve visibility.

Consider re-visiting once we have log aggregation and monitoring.

Or a re-work of the ingestion system for individualized dataset processing via some kind of orchestration engine that provides these kinds of things (such as Dagster). 

Closing.
