### ISSUE TITLE
systemd-journal issue after upgrading python libs with pip

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#107]
The code works fine when run interactively (`idigbio-ingestion -v --logfile ./manual.log update-publisher-recordset`), but when run as a systemd unit (`idigbio-ingestion-update-publisher-recordset.service
`) the journal logger complains about the unicode characters.

```
Aug 17 21:43:08 c18node4 idigbio-ingestion[23154]: Starting Publisher Feed: e3767b6a-ac91-49b9-9e69-bd2fa10caf42 http://collections.mnhn.fr/ipt/rss.do
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]: Update Publisher id:111 e3767b6a-ac91-49b9-9e69-bd2fa10caf42 'MNHN - Collections'
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]: Traceback (most recent call last):
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:   File "/usr/local/lib/python2.7/dist-packages/systemd/journal.py", line 602, in emit
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:     **extras)
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:   File "/usr/local/lib/python2.7/dist-packages/systemd/journal.py", line 456, in send
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:     args.extend(_make_line(key, val) for key, val in kwargs.items())
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:   File "/usr/local/lib/python2.7/dist-packages/systemd/journal.py", line 456, in <genexpr>
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:     args.extend(_make_line(key, val) for key, val in kwargs.items())
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:   File "/usr/local/lib/python2.7/dist-packages/systemd/journal.py", line 409, in _make_line
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]:     return field + '=' + str(value)
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 144: ordinal not in range(128)
Aug 17 21:43:09 c18node4 idigbio-ingestion[23154]: Logged from file update_publisher_recordset.py, line 311

```

I suspect that `systemd-python` was not actually on the workflow node. Or maybe this is due to `chardet` which I had to upgrade manually. There are some changes in the past 2 years related to systemd-python vs python-systemd.

We don't have this particular code running in a unit anywhere else.

Pip freeze diff before and after doing the upgrade:

```
diff c18node4.after.upgrade.pip.freeze.txt c18node4.pip.freeze.txt
15,16c15
< certifi==2020.6.20
< chardet==3.0.4
---
> chardet==2.3.0
43c42
< idna==2.7
---
> idna==2.0
64d62
< olefile==0.46
70c68
< Pillow-SIMD==4.3.0.post0
---
> Pillow-SIMD==5.1.1.post0
75d72
< psycopg2-binary==2.8.5
92c89
< pytest-mock==1.13.0
---
> pytest-mock==1.10.0
105c102
< requests==2.20.0
---
> requests==2.14.2
116d112
< systemd-python==234
121c117
< urllib3==1.24.3
---
> urllib3==1.13.1

```

**Comment by danstoner** [comment]
The issue is caused by the presence of `systemd-python`.

This was a semi-recent change IIRC (past two years), we have PRs / commits for adding that specifically.  Will need a little more research but for now I simply `pip uninstall systemd-python` on the workflow node where the service lives.

**Comment by danstoner** [comment]
Looks like this is a relevant commit:

https://github.com/iDigBio/idb-backend/commit/89fbfc71ae6dc42b6a5016daa4af711230a7056c

Also, I believe the package (ubuntu) for Salt minion requires a python lib `python-systemd` package.  I cannot remove that without removing (or breaking) salt minion.

This could explain some of the behavior differences.

**Comment by danstoner** [comment]
Fixed by using Ubuntu system package `python-systemd` instead of PyPi package `systemd-python`.

https://github.com/iDigBio/idb-backend/pull/108

**Comment by danstoner** [comment]
If we decide to revisit this to allow us to use `python-systemd` (do we care?), the fix might be as simple as this:
https://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python
