### ISSUE TITLE
indexer aborts with ConnectionError

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#112]
Indexing aborts with:

```
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
```

The server indicates:

```
HTTP content length exceeded 104857600 bytes.
```

**Comment by danstoner** [comment]
And apparently indexer does not retry on `ConnectionError`.

And there is a nice exception `TypeError` at the end.

```
18:23:26.498 WARNI elasticsearch჻ Connection <Urllib3HttpConnection: http://c20node12.acis.ufl.edu:9200> has failed for 1 times in a row, p
utting on 60 second timeout.
18:23:26.520 ERROR idb჻ Error in check
Traceback (most recent call last):
  File "/root/idb-backend/idb/helpers/logging.py", line 183, in _fnlogged
    return fn(*args, **kwargs)
  File "/root/idb-backend/idb/helpers/logging.py", line 166, in _fntimed
    result = fn(*args, **kwargs)
  File "/root/idb-backend/idb/indexing/__init__.py", line 170, in check
    resume(also_delete=True, **params)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 267, in resume
    consume(ei, rc, f, no_index=no_index)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 311, in consume
    for ok, item in ei.bulk_index(index_record_tuples):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
Traceback (most recent call last):
  File "/usr/local/bin/idb", line 11, in <module>
    load_entry_point('idb-backend', 'console_scripts', 'idb')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/root/idb-backend/idb/helpers/logging.py", line 183, in _fnlogged
    return fn(*args, **kwargs)
  File "/root/idb-backend/idb/helpers/logging.py", line 166, in _fntimed
    result = fn(*args, **kwargs)
  File "/root/idb-backend/idb/indexing/__init__.py", line 170, in check
    resume(also_delete=True, **params)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 267, in resume
    consume(ei, rc, f, no_index=no_index)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 311, in consume
    for ok, item in ei.bulk_index(index_record_tuples):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
Exception TypeError: TypeError('signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object',) in <generator object rate_logger at 0x7fe7ba30e4b0> ignored
```

**Comment by danstoner** [comment]
indexer is stopping shortly after:

```
21:02:15.144 INFO  idb.index_from_postgres჻ mediarecords indexing 9610000 6824.1/s
```

**Comment by danstoner** [comment]
Excerpts from highly verbose logs with chunk_size of 10:

```
...-2.10.20","_type":"mediarecords","_id":"f7459c1f-cec4-4346-8895-45849e46703e","_score":null,"_routing":"385cba7b-e18a-493b-8906-b7942a5bff93","_parent":"385cba7b-
e18a-493b-8906-b7942a5bff93","_source":{"etag":"2bf0360bb6d27e0989c19006d2991015f11d07de"},"sort":[4299154]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_
id":"74345808-d632-4eab-8cc6-3287b8085836","_score":null,"_routing":"51c5ad82-0e62-484f-9a98-a3598e91c50f","_parent":"51c5ad82-0e62-484f-9a98-a3598e91c50f","_sour
ce":{"etag":"615fbea565d78fdf813a63031c41f3d92b44f37d"},"sort":[4299155]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"08071f1f-5863-4e43-b63b-9a34f8
21f73e","_score":null,"_routing":"9130fc11-02a7-42ca-8278-ce97fc7d8fb4","_parent":"9130fc11-02a7-42ca-8278-ce97fc7d8fb4","_source":{"etag":"0f08ec124b2974051096b4
330c30b22678ab84ee"},"sort":[4299156]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"3c544640-3f64-4fc2-b172-ca3068e3ffe0","_score":null,"_routing":"7
271ddbe-b962-48b2-8ee5-6ba8fccc1d50","_parent":"7271ddbe-b962-48b2-8ee5-6ba8fccc1d50","_source":{"etag":"2c528aadd4c4306ddc17a3a5d7fe889e6cb8d4e2"},"sort":[429915
7]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"9a6f2cf1-e96d-4a2b-bfe7-a6c4d5e2f465","_score":null,"_routing":"db36b6fa-5b6a-450e-8e35-a0de3050f7a7
","_parent":"db36b6fa-5b6a-450e-8e35-a0de3050f7a7","_source":{"etag":"db41c1cbd825e10d90a75ec64e508a3ced731967"},"sort":[4299158]},{"_index":"idigbio-2.10.20","_t
ype":"mediarecords","_id":"07a41a2e-8c70-4333-9293-4821ef22a388","_score":null,"_routing":"5cc7f85f-deae-4a4e-9300-83d3cdc16677","_parent":"5cc7f85f-deae-4a4e-930
0-83d3cdc16677","_source":{"etag":"7d1ffff76ed5030de392b0130739af8ecaa68905"},"sort":[4299159]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"35921749
-a403-4afd-a1d8-ae722e04ba71","_score":null,"_routing":"e00331d8-d808-4b72-a28a-f1b0e7a91058","_parent":"e00331d8-d808-4b72-a28a-f1b0e7a91058","_source":{"etag":"
20c5ed1aa5b18134bd7bd426aa06b23dc94c86d0"},"sort":[4299160]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"9a479b9f-5ce9-4192-bcb3-7648b684a394","_sco
re":null,"_routing":"e00331d8-d808-4b72-a28a-f1b0e7a91058","_parent":"e00331d8-d808-4b72-a28a-f1b0e7a91058","_source":{"etag":"abc6212bbfc2ce508a0e5a2f0b33d61bb08
2196c"},"sort":[4299161]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"ba886079-5d36-446b-a955-2dad10be5a3a","_score":null,"_routing":"48c70a48-b593-
4db0-8945-aca4a72a5f38","_parent":"48c70a48-b593-4db0-8945-aca4a72a5f38","_source":{"etag":"2d00f4f0019f9cd5e55bafda271781661ebbd973"},"sort":[4299162]},{"_index"
:"idigbio-2.10.20","_type":"mediarecords","_id":"173b265f-9940-4792-963f-6fb078b556b1","_score":null,"_routing":"a2c556f5-2a40-4b7f-9bdd-4504f8888453","_parent":"
a2c556f5-2a40-4b7f-9bdd-4504f8888453","_source":{"etag":"70097fb9d132c1f6ca73a20e3620a96abbe83757"},"sort":[4299163]},{"_index":"idigbio-2.10.20","_type":"mediare
cords","_id":"d7436b65-fc38-4a73-8851-9da4b52876e2","_score":null,"_routing":"a2c556f5-2a40-4b7f-9bdd-4504f8888453","_parent":"a2c556f5-2a40-4b7f-9bdd-4504f888845
3","_source":{"etag":"73043e3e692e76c163997f1d2c99da458d7b12d6"},"sort":[4299164]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"085451ad-5813-4496-86
fe-559a446474d1","_score":null,"_routing":"6b7e1ce8-2890-4f91-9bc7-16093491cbd5","_parent":"6b7e1ce8-2890-4f91-9bc7-16093491cbd5","_source":{"etag":"043cd5b832cf9
4bc74df751ae05bf2ea3ed78a4a"},"sort":[4299165]},{"_index":"idigbio-2.10.20","_type":"mediarecords","_id":"99bfe46b-fc95-4499-93bb-75f4e818db62","_score":null,"_routing":"38ee363d-a134-4aea-814c-a069bc9c613e","_parent":"38ee363d-a134-4aea-814c-a069bc9c613e","_source":{"etag":"585c461fb897232f527361790b704fede2b04d14"},"sort":[4299166]}]}}
12:50:50.740 DEBUG urllib3.util.retry჻ Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
12:50:50.746 DEBUG urllib3.connectionpool჻ http://c20node1.acis.ufl.edu:9200 "GET /_search/scroll?scroll=10m HTTP/1.1" 200 2247
12:50:50.746 INFO  elasticsearch჻ GET http://c20node1.acis.ufl.edu:9200/_search/scroll?scroll=10m [status:200 request:0.006s]
12:50:50.747 DEBUG elasticsearch჻ > {"scroll_id": "cXVlcnlUaGVuRmV0Y2g7NDg7NDgx...
```

**Comment by danstoner** [comment]
Seems that this must be a large document.  Attempting to narrow down the culprit. These are posted through the bulk indexer and don't have good debug logging around that yet.

**Comment by danstoner** [comment]
After running indexing successfully with a small chunk size, this issue has not re-occurred.  Closing.
