### ISSUE TITLE
idigbio_ingestion/lib/dwca.py - AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#139]
While running `db-check`.

Not caught by test suite.

```
UUID=f266a75c-3529-4868-8669-9f98822e033f TYP=db-check bash -c 'idigbio-ingestion -v --logfile ./$TYP_$UUID.`date +"%Y-%m-%d_%H%M%S"`.log $TYP $UUID'
2021-04-02 10:52:06.167 INFO  idb.db-check.f266a75c-3529-4868-8669-9f98822e033f჻ Starting db_check ingest: False
2021-04-02 10:52:06.199 INFO  idb.db-check.f266a75c-3529-4868-8669-9f98822e033f჻ Processing f266a75c-3529-4868-8669-9f98822e033f, type: application/zip
2021-04-02 10:52:07.045 ERROR idb.db-check჻ Unhandled Exception when processing f266a75c-3529-4868-8669-9f98822e033f
Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/db_check.py", line 443, in process_file
    dwcaobj = Dwca(fname, skipeml=True, logname="idb")
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/lib/dwca.py", line 92, in __init__
    logname=self.logger.name)
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/lib/dwca.py", line 176, in __init__
    fieldsplit = filedict["#fieldsTerminatedBy"].decode('string_escape')
AttributeError: 'str' object has no attribute 'decode'
2021-04-02 10:52:07.045 INFO  idb.db-check჻ f266a75c-3529-4868-8669-9f98822e033f writing summary json
2021-04-02 10:52:07.126 INFO  idb.db-check.f266a75c-3529-4868-8669-9f98822e033f჻ Finished db_check in 0.958s

```

**Comment by danstoner** [comment]
Resolved by 1d92c5b30af791536bfbcc1c11c22200e5b280d5
