### ISSUE TITLE
py3 issues in update_publisher_recordset.py

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#152]
Looks like the code is trying to use the contents as the filename.

```
2021-04-06 14:30:35.541 INFO  idb.upr჻ *** Begin harvest of eml files...
2021-04-06 14:30:35.998 INFO  idb.upr჻ Harvesting 1024 EML files
2021-04-06 14:30:35.999 INFO  idb.upr჻ Harvest EML 2630 'UFMT - Herbário UFMT - Version 1.4' @ 'http://ipt1.cria.org.br/ipt/eml.do?r=ufmt'
2021-04-06 14:30:36.617 ERROR idb.upr჻ failed Harvest EML 2630 UFMT - Herbário UFMT - Version 1.4
Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 416, in harvest_all_eml
    harvest_eml(r, db)
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 440, in harvest_eml
    desc = parseEml(r["recordids"][0], inf.read())
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/lib/eml.py", line 21, in parseEml
    eml = pq(filename=emlFilename, parser='xml')
  File "/home/dan/git/IDIGBIO/idb-backend/.direnv/lib/python3.6/site-packages/pyquery/pyquery.py", line 178, in __init__
    html = open(kwargs['filename'])
OSError: [Errno 36] File name too long: b'<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"\n         xmlns:dc="http://purl.org/dc/terms/"\n         xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta
2021-04-06 14:30:36.621 INFO  idb.upr჻ Harvest EML 2660 'OUPR - Herbário "Professor José Badini" - Version 1.3' @ 'http://ipt1.cria.org.br/ipt/eml.do?r=oupr'
2021-04-06 14:30:37.206 ERROR idb.upr჻ failed Harvest EML 2660 OUPR - Herbário "Professor José Badini" - Version 1.3
Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/update_publisher_recordset.py", line 416, in harvest_all_eml

```

Also a little nervous about the large number of EML files it is trying to download (`1024`).

**Comment by danstoner** [comment]
Pyquery in python3 wants a str, bytes or os.PathLike object. We were previously wrapping that operation with a "with open(file) as f" kind of pattern.

Changed our eml processing code to let pyquery open the file itself in 4b2412ee69e1702277a1c97d00e7005ef4f57188

update-publisher-recordset looks good to go.
