### ISSUE TITLE
idigbio-ingestion update-publisher-recordset takes very long time for timeouts

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#156]
Not clear whether this is just due to python3 testing locally on laptop over VPN, or if there is an issue with these timeouts taking much longer under python3.

Also seeing these exceptions:

```
Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/git/IDIGBIO/idb-backend/idigbio_ingestion/lib/util.py", line 9, in download_file
    r = s.get(url, params=params, stream=True, timeout=timeout)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/dan/git/IDIGBIO/idb-backend/.venvpy3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by danstoner** [comment]
This is not a real issue, just appeared to take a long time due to log level omitting evidence of activity.
