### ISSUE TITLE
Adjust download blocker task retries to a sensible number

### ISSUE THREAD

**Issue by nrejack** [iDigBio/idb-backend#170]
https://github.com/iDigBio/idb-backend/blob/4cf5efe4a661c0c95e6346d5ba36792460f93221/idigbio_workers/tasks/download.py#L81

The download blocker issue currently never stops retrying. There is a reference in the commit message that says these were terminating early. However, retrying endlessly can result in stuck tasks that never time out.

Adjust to a sensible number, preferably one that can be tweaked at run time.

**Comment by danstoner** [comment]
The "download all of idigbio" task seems like it would need a very large number of retries.  Or maybe I don't understand what this actually works.

I don't know what this comment really means, either:

```
This can be used to append tasks to a running one, block on the
    running and chain after this.
```

**Comment by danstoner** [comment]
Reading some more of the context in our Slack...

If an exception is being "swallowed" and we keep retrying the same task, it seems like that is a bug that maybe ought to be fixed.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/idb-backend/idigbio_workers/tasks/download.py", line 94, in blocker
    countdown=pollbase ** self.request.retries)
  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 687, in retry
    raise ret
Retry: Retry in 108.420217249s
```
