### ISSUE TITLE
db_check.log always logs exception and traceback at end of file

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#26]
It appears that the iterator always logs an exception when it gets to the end of the file.

We probably do not want on exception in that case.  Logfiles without actual errors should be "clean".

```
2017-05-21 20:59:55.738 INFO  idb.db-check.f39780bd-7108-4685-8e6a-b340ff5a5965჻ Starting db_check ingest: True
2017-05-21 20:59:55.839 INFO  idb.db-check.f39780bd-7108-4685-8e6a-b340ff5a5965჻ Processing f39780bd-7108-4685-8e6a-b340ff5a5965, type: application/zip
2017-05-21 20:59:56.487 DEBUG idb.db-check.f39780bd-7108-4685-8e6a-b340ff5a5965჻ processing core 'f39780bd-7108-4685-8e6a-b340ff5a5965_extracted/occurrence.txt'
2017-05-21 21:00:02.709 WARNI idb.f39780bd-7108-4685-8e6a-b340ff5a5965.occurrence჻ OtherException : f39780bd-7108-4685-8e6a-b340ff5a5965_extracted/occurrence.txt Line 20419 (52)
2017-05-21 21:00:02.710 INFO  idb.f39780bd-7108-4685-8e6a-b340ff5a5965.occurrence჻ Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/lib/delimited.py", line 129, in readline
    lineArr = self._reader.next()
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 117, in next
    row = self.reader.next()
StopIteration

2017-05-21 21:00:02.733 INFO  idb.db-check.f39780bd-7108-4685-8e6a-b340ff5a5965჻ Ready to Commit
2017-05-21 21:00:02.734 INFO  idb.db-check჻ f39780bd-7108-4685-8e6a-b340ff5a5965 writing summary json
2017-05-21 21:00:02.793 INFO  idb.db-check.f39780bd-7108-4685-8e6a-b340ff5a5965჻ Finished db_check in 7.054s
```

**Comment by danstoner** [comment]
Fixed via f005c081d45ccb35b3d22a111f05ad71f0da880f

We now get a single debug logline without traceback:

```
09:58:16.019 DEBUG idb.c4f0b43b-1a43-43bc-b302-2aecd37d8054.occurrence჻ Finished File (StopIteration reached)
```
