### ISSUE TITLE
indexer failing with "Error in uuids"

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#36]
While trying to process iDigBio recordset uuid ```b40e13f7-a79a-4265-93d9-3b4878dfc988```

```
root@c18node4:/mnt/data/new_ingestion# cat index-b40e13f7-a79a-4265-93d9-3b4878dfc988.2018-06-15_105833.log
2018-06-15 10:58:34.405 INFO  idb.indexing჻ Initializing ElasticSearchIndexer(u'2.10.12', [u'publishers', u'recordsets', u'mediarecords', u'records'])
2018-06-15 11:07:58.713 ERROR idb჻ Error in uuids
Traceback (most recent call last):
  File "/root/idb-backend/idb/helpers/logging.py", line 183, in _fnlogged
    return fn(*args, **kwargs)
  File "/root/idb-backend/idb/helpers/logging.py", line 166, in _fntimed
    result = fn(*args, **kwargs)
  File "/root/idb-backend/idb/indexing/__init__.py", line 122, in uuids
    uuids(children=children, uuid_l=uuid, **params)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 309, in uuids
    consume(ei, rc, f, no_index=no_index)
  File "/root/idb-backend/idb/indexing/index_from_postgres.py", line 329, in consume
    for ok, item in ei.bulk_index(index_record_tuples):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'1 document(s) failed to index.', [{u'delete': {u'status': 404, u'_type': u'records', u'_shards': {u'successful': 3, u'failed': 0, u'total': 3}, u'_index': u'idigbio-2.10.12', u'_version': 1, u'found': False, u'_id': u'd5468f7e-db0b-4f99-a2c7-c8ec6ca584ee'}}])
```

**Comment by danstoner** [comment]
Database records look "clean".  The record uuid is marked as deleted, the data etag is properly tombstoned.

```
idb_api_prod=> select * from uuids where id = 'd5468f7e-db0b-4f99-a2c7-c8ec6ca584ee';
                  id                  |  type  |                parent                | deleted 
--------------------------------------+--------+--------------------------------------+---------
 d5468f7e-db0b-4f99-a2c7-c8ec6ca584ee | record | b40e13f7-a79a-4265-93d9-3b4878dfc988 | t
(1 row)

idb_api_prod=> select * from uuids_data where uuids_id = 'd5468f7e-db0b-4f99-a2c7-c8ec6ca584ee';
    id     |               uuids_id               |                data_etag                 |          modified          | version
-----------+--------------------------------------+------------------------------------------+----------------------------+---------
 719061380 | d5468f7e-db0b-4f99-a2c7-c8ec6ca584ee | 9a4e35834eb80d9af64bcd07ed996b9ec0e60d92 | 2017-09-30 10:07:17.707392 |       2
 547036361 | d5468f7e-db0b-4f99-a2c7-c8ec6ca584ee | 94640d0830bd1647dfdcb46196d6e0363520de4f | 2016-09-07 15:29:00.172359 |       1
 538601568 | d5468f7e-db0b-4f99-a2c7-c8ec6ca584ee | 4afadfd2f93d2ce194fa958bfe0fbf8436b0b4a8 | 2016-08-02 13:30:21.810687 |       0
(3 rows)
```

**Comment by danstoner** [comment]
That uuid `d5468f7e-db0b-4f99-a2c7-c8ec6ca584ee` is not present in the index, either (idigbio-2.10.13).

**Comment by danstoner** [comment]
Hmmm... the original error report was index version 2.10.12.  Wonder if this is still a problem?

Portal shows recordset was indexed recently.

https://www.idigbio.org/portal/recordsets/b40e13f7-a79a-4265-93d9-3b4878dfc988

The indexer log has no error of this kind.

Closing.
