### ISSUE TITLE
IOError missing file world_borders.shp

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#37]
```
Traceback (most recent call last):
  File "/usr/local/bin/idb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/logging.py", line 183, in _fnlogged
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/logging.py", line 166, in _fntimed
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/idb/indexing/__init__.py", line 122, in uuids
    uuids(children=children, uuid_l=uuid, **params)
  File "/usr/local/lib/python2.7/dist-packages/idb/indexing/index_from_postgres.py", line 309, in uuids
    consume(ei, rc, f, no_index=no_index)
  File "/usr/local/lib/python2.7/dist-packages/idb/indexing/index_from_postgres.py", line 329, in consume
    for ok, item in ei.bulk_index(index_record_tuples):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 161, in streaming_bulk
    for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 55, in _chunk_actions
    for action, data in actions:
  File "/usr/local/lib/python2.7/dist-packages/idb/indexing/indexer.py", line 140, in bulk_formater
    for t, i in tups:
  File "/usr/local/lib/python2.7/dist-packages/idb/indexing/index_helper.py", line 34, in index_record
    g = grabAll(typ, d)
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/conversions.py", line 921, in grabAll
    r.update(geoGrabber(t, d))  # 4
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/conversions.py", line 491, in geoGrabber
    result = get_country(r["geopoint"][0], r["geopoint"][1], eez=False)
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/rg.py", line 78, in get_country
    return get_rg().get_country(lon, lat)
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/memoize.py", line 16, in memo
    memo.__cache__ = fn()
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/rg.py", line 55, in get_rg
    return ReverseGeocoder()
  File "/usr/local/lib/python2.7/dist-packages/idb/helpers/rg.py", line 24, in __init__
    with fiona.open(path) as shp:
  File "/usr/local/lib/python2.7/dist-packages/fiona/__init__.py", line 165, in open
    raise IOError("no such file or directory: %r" % path)
IOError: no such file or directory: '/usr/local/lib/python2.7/dist-packages/idb/helpers/data/world_borders.shp'
```

**Comment by danstoner** [comment]
on the workflow node.

**Comment by danstoner** [comment]
Probably caused by running:

```
python setup.py bdist_egg
```

Re-cloned the repo, installed using known good procedure

```
pip install -r requirements.txt
```

All is good.

Closing.
