### ISSUE TITLE
debug line output fails on utf-8 identifiers

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#38]
```
13:11:42.951 ERROR idb.db-check.616857b7-f952-44ef-9b6f-576dc1e65b51჻ Uncaught exception handling {'dwc:countryCode': u'sg', 'dwc:recordedBy': u'Langlass\xe9, E.', 'dwc:fieldNumber': u'41', 'dwc:verbatimLocality': u'Kranji', 'dwc:occurrenceID': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00750911\xb2', 'dwc:fieldNotes': u'Arbrisseau \xe0 tige sarmenteux', 'dwc:institutionCode': u'MNHN', 'id': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00750911\xb2', 'dwc:catalogNumber': u'P00750911\xb2', 'gbif:Identifier': [{'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00750911\xb2', 'dcterms:identifier': u'3CA327BDB819402CA5187A9B2A4CA441', 'dcterms:subject': u'e-recolnat'}], 'dcterms:modified': u'2015-09-05 09:42:17.0', 'dwc:Identification': [{'dwc:taxonID': u'SONNERAT|71601', 'dwc:identificationVerificationStatus': u'1', 'dwc:specificEpithet': u'sp.', 'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00750911\xb2', 'dwc:identificationID': u'SONNERAT|1272829', 'dwc:genus': u'Fissistigma', 'dwc:scientificName': u'Fissistigma sp.', 'dwc:higherClassification': u'Fissistigma;Annonaceae', 'dwc:family': u'Annonaceae'}], 'dwc:eventDate': u'1894-7-24', 'dwc:month': u'7', 'dwc:country': u'Singapore', 'dwc:collectionCode': u'P', 'dwc:preparations': u'hb', 'dwc:basisOfRecord': u'PreservedSpecimen', 'dwc:genus': u'Fissistigma', 'dwc:scientificName': u'Fissistigma sp.', 'dwc:day': u'24', 'dwc:family': u'Annonaceae', 'dwc:year': u'1894'}
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 220, in process_subfile
    logger.debug("#### ident | ident[2] #### : {0} | {1}'".format(ident, ident[2]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 88: ordinal not in range(128)
13:38:45.864 ERROR idb.db-check.616857b7-f952-44ef-9b6f-576dc1e65b51჻ Uncaught exception handling {'dwc:countryCode': u'fr', 'dwc:recordedBy': u'Vaillant, S.', 'dwc:verbatimLocality': u's.l.', 'dwc:scientificNameAuthorship': u'(L.) Loisel.', 'dwc:occurrenceID': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00447382\xb2', 'dwc:institutionCode': u'MNHN', 'id': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00447382\xb2', 'dwc:catalogNumber': u'P00447382\xb2', 'gbif:Identifier': [{'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00447382\xb2', 'dcterms:identifier': u'90130837BF084B3799E8BBDEF416E128', 'dcterms:subject': u'e-recolnat'}], 'dcterms:modified': u'2015-09-16 00:48:42.0', 'dwc:Identification': [{'dwc:taxonID': u'SONNERAT|56951', 'dwc:identificationVerificationStatus': u'1', 'dwc:specificEpithet': u'procumbens', 'dwc:identificationID': u'SONNERAT|489842', 'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00447382\xb2', 'dwc:scientificNameAuthorship': u'(L.) Loisel.', 'dwc:genus': u'Loiseleuria', 'dwc:scientificName': u'Loiseleuria procumbens (L.) Loisel.', 'dwc:higherClassification': u'Loiseleuria;Ericaceae', 'dwc:family': u'Ericaceae'}], 'dwc:country': u'France', 'dwc:collectionCode': u'P', 'dwc:preparations': u'hb', 'dwc:basisOfRecord': u'PreservedSpecimen', 'dwc:genus': u'Loiseleuria', 'dwc:scientificName': u'Loiseleuria procumbens (L.) Loisel.', 'dwc:family': u'Ericaceae'}
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 220, in process_subfile
    logger.debug("#### ident | ident[2] #### : {0} | {1}'".format(ident, ident[2]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 88: ordinal not in range(128)


14:00:29.743 ERROR idb.db-check.616857b7-f952-44ef-9b6f-576dc1e65b51჻ Uncaught exception handling {'dwc:countryCode': u'se', 'dwc:recordedBy': u'Stenhammer', 'dwc:verbatimLocality': u'Stockholm', 'dwc:scientificNameAuthorship': u'L.', 'dwc:occurrenceID': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00515707\xb2', 'dwc:institutionCode': u'MNHN', 'id': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00515707\xb2', 'dwc:catalogNumber': u'P00515707\xb2', 'gbif:Identifier': [{'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00515707\xb2', 'dcterms:identifier': u'719122863DBC4EC8A118E5DD18FF083A', 'dcterms:subject': u'e-recolnat'}], 'dcterms:modified': u'2016-03-17 12:22:28.0', 'dwc:Identification': [{'dwc:taxonID': u'SONNERAT|10073', 'dwc:identificationVerificationStatus': u'1', 'dwc:specificEpithet': u'officinalis', 'dwc:identificationID': u'SONNERAT|577992', 'coreid': u'http://coldb.mnhn.fr/catalognumber/mnhn/p/p00515707\xb2', 'dwc:scientificNameAuthorship': u'L.', 'dwc:genus': u'Pulmonaria', 'dwc:scientificName': u'Pulmonaria officinalis L.', 'dwc:higherClassification': u'Pulmonaria;Boraginaceae', 'dwc:family': u'Boraginaceae'}], 'dwc:eventDate': u'1834', 'dwc:country': u'Su\xe8de', 'dwc:collectionCode': u'P', 'dwc:preparations': u'hb', 'dwc:basisOfRecord': u'PreservedSpecimen', 'dwc:genus': u'Pulmonaria', 'dwc:scientificName': u'Pulmonaria officinalis L.', 'dwc:family': u'Boraginaceae', 'dwc:year': u'1834'}
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 220, in process_subfile
    logger.debug("#### ident | ident[2] #### : {0} | {1}'".format(ident, ident[2]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 88: ordinal not in range(128)
```

When processing Paris:
https://www.idigbio.org/portal/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51

**Comment by danstoner** [comment]
Other examples:
```
# grep -l ascii *.log
20360fae-574a-4d63-b9f6-47b1cc07fd22.db_check.log
38db50bb-72f3-4416-aeb9-61457e655a6d.db_check.log
53091d18-f173-4fc0-b9d9-20a1494e2466.db_check.log
5e893602-84ca-4c8c-bac1-99111c777582.db_check.log
616857b7-f952-44ef-9b6f-576dc1e65b51.db_check.log
b17204ee-8a17-4ba1-9e74-bfadca6dce08.db_check.log
c804f67a-efed-4ff6-a875-dc132a040058.db_check.log
dd1b8c0b-280f-4cd3-979a-ad7464c5c9b5.db_check.log
f778ecc0-8371-49d5-9ab1-9d75f0b76fad.db_check.log
```

**Comment by danstoner** [comment]
Some of these are apparent errors (accidental unicodes at the end of a catalog number, for example).

Others might be legitimate:

```
2018-08-19 12:00:28.576 ERROR idb.db-check.c804f67a-efed-4ff6-a875-dc132a040058჻ Uncaught exception handling {'dwc:specificEpithet': u'sp.', 'dwc:kingdom': u'Plantae', 'dwc:recordedBy': u'D.P.Santos, M.T.Fujii, D.Bacci
, M.B.Barreto, G.A.F', 'dwc:order': u'Acrochaetiales', 'dwc:occurrenceID': u'BRA:IBt:SP-ALGAE:N\xc3O TEM SP', 'dcterms:language': u'pt', 'dcterms:rightsHolder': u'SP-Algae - Herb\xe1rio do Estado "Maria Eneyda P. Kaufm
ann Fidalgo - Cole\xe7\xe3o de Algas', 'dwc:stateProvince': u'S\xe3o Paulo', 'dwc:country': u'Brasil', 'dwc:collectionCode': u'SP-ALGAE', 'dwc:verbatimLatitude': u'23\xba 50\' 25"S', 'id': u'BRA:IBt:SP-ALGAE:N\xc3O TEM
 SP', 'dwc:decimalLatitude': u'-23.8402780000000014', 'dwc:occurrenceRemarks': u'Obs:Ereto Reprodutor Marinho: N\xe3o determinado Ambiente: marinha', 'dwc:basisOfRecord': u'PreservedSpecimen', 'dwc:genus': u'Acrochaeti
um', 'dwc:family': u'Acrochaetiaceae', 'dwc:identifiedBy': u'S.M.P.B. Guimar\xe3es', 'dwc:municipality': u'Ubatuba', 'dcterms:license': u'Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.', 'dwc:owner
InstitutionCode': u'Instituto de Bot\xe2nica, IBT', 'dwc:phylum': u'Rhodophyta', 'dwc:locality': u'Praia Brava', 'dwc:institutionCode': u'IBt', 'dwc:class': u'Rhodophyceae', 'dwc:catalogNumber': u'N\xc3O TEM SP', 'dcte
rms:type': u'Collection', 'dwc:month': u'03', 'dwc:decimalLongitude': u'-45.2899999999999991', 'dwc:verbatimLongitude': u'45\xba 17\' 24"W', 'dwc:datasetName': u'SP-Algae - Herb\xe1rio do Estado "Maria Eneyda P. Kaufma
nn Fidalgo - Cole\xe7\xe3o de Algas', 'dcterms:modified': u'2014-04-04 12:27:09-03', 'dwc:scientificName': u'Acrochaetium sp.', 'dwc:day': u'12', 'dwc:year': u'2001'}
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 220, in process_subfile
    logger.debug("#### ident | ident[2] #### : {0} | {1}'".format(ident, ident[2]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 55: ordinal not in range(128)

```

Regardless, we should try not to get UnicodeEncodeError when writing debug lines.
