### ISSUE TITLE
db_check recordset disambiguation

### ISSUE THREAD

**Issue by UnwashedMeme** [iDigBio/idb-backend#4]
In the current code https://github.com/iDigBio/idb-backend/blob/master/idigbio_ingestion/db_check.py  takes a recordset id, forms the url `http://api.idigbio.org/v1/recordsets/$RSID` out of it and then looks that up in the media_objects to get the etag of the file to fetch. There can (and are) recordsets that have more than one version of the file stored but the current code provides no ordering in the query and just selects the first one.

1. https://github.com/iDigBio/idb-backend/blob/0aa3f1f/idigbio_ingestion/db_check.py#L90
2. https://github.com/iDigBio/idb-backend/blob/0aa3f1f/idb/helpers/storage.py#L102

**Comment by UnwashedMeme** [comment]
Talked with Alex about this:

Logically we want to select the most recent `media_object` row for that url by `media_object.modified` and get that etag. However the `recordsets` table should have that value cached as `recordsets.file_harvest_etag`

**Comment by UnwashedMeme** [comment]
This issue is mostly resolved, but there is some more cleanup that we could disambiguate the `MediaObject.fromurl` function that used to be used here to get the latest by modified.

**Comment by UnwashedMeme** [comment]
We also updated the `media_object_url` index in the DB to be on `url, modified` to make the query in 3624118 work better

**Comment by UnwashedMeme** [comment]
```
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 516, in <module>
    main()
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 495, in main
    name, mime = get_file(rsid)
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 90, in get_file
    RecordSet.fetch_file(rsid, fname, media_store=IDigBioStorage())
  File "/root/idb-backend/idb/postgres_backend/db.py", line 699, in fetch_file
    raise ValueError("Recordset {0!r} doesn't have a stored object")
ValueError: Recordset {0!r} doesn't have a stored object
Traceback (most recent call last):
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 516, in <module>
    main()
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 495, in main
    name, mime = get_file(rsid)
  File "/root/idb-backend/idigbio_ingestion/db_check.py", line 90, in get_file
    RecordSet.fetch_file(rsid, fname, media_store=IDigBioStorage())
  File "/root/idb-backend/idb/postgres_backend/db.py", line 699, in fetch_file
    raise ValueError("Recordset {0!r} doesn't have a stored object")
ValueError: Recordset {0!r} doesn't have a stored object
```
