### ISSUE TITLE
blocker on python 3 upgrade - cStringIO

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#45]
When running update_publisher_recordset.py in a clean virtual environment:

```Traceback (most recent call last):
  File "update_publisher_recordset.py", line 14, in <module>
    from idb.postgres_backend.db import PostgresDB, MediaObject, DictCursor
  File "/home/dan/git/idb-backend/idb/postgres_backend/db.py", line 10, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'
```

See
https://stackoverflow.com/a/18284900

short-term workaround is to make sure to use Python 2.x inside the virtual environment.

**Comment by danstoner** [comment]
Python3 upgrade is in-progress for this repo (development branch is `convert_python_3`) which will fix this and many many other issues with python 3.

**Comment by danstoner** [comment]
Not really a blocker, just something that needs to be addressed throughout the codebase.

Closing.
