### ISSUE TITLE
Extremely large images kill mediaing derivatives service

### ISSUE THREAD

**Issue by nrejack** [iDigBio/idb-backend#58]
Running the mediaing derivatives service fails on extremely large images >178956970 px, causing service to fail. No further derivatives are generated after this happens. The source images may in fact be valid, but are just too large.

```
root@workflow_node:~# journalctl -u idigbio-ingestion-derivatives.service --since "yesterday"
...snip...
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]: Traceback (most recent call last):
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/bin/idigbio-ingestion", line 11, in <module>
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     load_entry_point('idb-backend', 'console_scripts', 'idigbio-ingestion')()
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     return self.main(*args, **kwargs)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     rv = self.invoke(ctx)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     return ctx.invoke(self.callback, **ctx.params)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     return callback(*args, **kwargs)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idb/helpers/logging.py", line 183, in _fnlogged
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     return fn(*args, **kwargs)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idb/helpers/logging.py", line 166, in _fntimed
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     result = fn(*args, **kwargs)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idigbio_ingestion/mediaing/cli.py", line 65, in derivatives
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     derivatives.main(bucket, procs=procs)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idigbio_ingestion/mediaing/derivatives.py", line 65, in main
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     process_objects(objects)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idigbio_ingestion/mediaing/derivatives.py", line 91, in process_objects
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     autocommit=True
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 181, in executemany
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     cursor.executemany(*args)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idigbio_ingestion/mediaing/derivatives.py", line 87, in <genexpr>
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     etags = ((gr.etag,) for gr in results if gr)
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/root/idb-backend/idigbio_ingestion/mediaing/derivatives.py", line 127, in count_results
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     for count, result in enumerate(results, 1):
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:   File "/usr/local/lib/python2.7/dist-packages/gevent/pool.py", line 102, in next
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]:     raise value.exc
Nov 21 00:03:56 c18node4 idigbio-ingestion[28274]: PIL.Image.DecompressionBombError: Image size (231243936 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
Nov 21 00:03:56 c18node4 systemd[1]: idigbio-ingestion-derivatives.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 00:03:56 c18node4 systemd[1]: Failed to start iDigBio mediaing derivatives generation.

```

**Comment by danstoner** [comment]
Based on loglines, I believe this is the offending image:

s.idigbio.org/idigbio-images-prod-fullsize/00a16012d668ca64769c182101443dbc.jpg

Opened in Gimp and dimensions are...

Size in pixels: 4912 x 7360 pixels
File size: 2.9 MB
Size in memory: 342 MB
Number of pixels: 36152320

![Screenshot from 2019-11-26 11-32-14](https://user-images.githubusercontent.com/2325459/69653067-9d3a0c80-1040-11ea-9f94-e4fca5a05098.png)

**Comment by danstoner** [comment]
I already changed number of procs to 1 but this thing may run in threads, so maybe that isn't the offending image.

**Comment by roncanepa** [comment]
The properties on that do seem quite odd.  With ~20" x 30" @ 240 ppi, I'd think it'd be a lot larger in filesize.

**Comment by danstoner** [comment]
*this* is the one triggering the decompression bomb:

s.idigbio.org/idigbio-images-prod/757d87e209cc3acc54e28f62bb095d02

I have to close some apps before I try to open it.  34MB file size.

**Comment by danstoner** [comment]
Changed code to handle exception gracefully.

If we actually want to increase the allowed size, this may be helpful:
https://stackoverflow.com/questions/51152059/pillow-in-python-wont-let-me-open-image-exceeds-limit

**Comment by nrejack** [comment]
Currently 141 images that exceed the limit. Recommended to not increase allowed size at this time, closing as successful.

**Comment by roncanepa** [comment]
Count today is 183 and will keep increasing (especially as technology improves).
