### ISSUE TITLE
Mediaing fetcher service stops fetching images if connection to database server fails

### ISSUE THREAD

**Issue by nrejack** [iDigBio/idb-backend#60]
After a failed connection to database server, mediaing fetcher service stops fetching images. Service does NOT appear in output of "systemctl --failed" however.

Relevant lines from journalctl (note: hostname of database server replaced in below log lines): 

```
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]: Traceback (most recent call last):
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/bin/idigbio-ingestion", line 11, in <module>
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     load_entry_point('idb-backend', 'console_scripts', 'idigbio-ingestion')()
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return self.main(*args, **kwargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     rv = self.invoke(ctx)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return ctx.invoke(self.callback, **ctx.params)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return callback(*args, **kwargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return f(get_current_context().obj, *args, **kwargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/helpers/logging.py", line 183, in _fnlogged
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return fn(*args, **kwargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/helpers/logging.py", line 166, in _fntimed
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     result = fn(*args, **kwargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idigbio_ingestion/mediaing/cli.py", line 37, in mediaing_get_media
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     fetcher.continuous(**mediaing_params)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idigbio_ingestion/mediaing/fetcher.py", line 94, in continuous
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     groups = group_by_prefix(fetchitems)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idigbio_ingestion/mediaing/fetcher.py", line 164, in group_by_prefix
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return [(prefix, list(r)) for prefix, r in itertools.groupby(items, lambda x: x.prefix)]
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idigbio_ingestion/mediaing/fetcher.py", line 150, in get_items
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     logger.debug("Querying %r", apidbpool.mogrify(sql, params))
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 163, in mogrify
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     with self.cursor(**kwargs) as cur:
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return self.gen.next()
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 159, in cursor
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     with self.connection(**connargs) as conn:
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return self.gen.next()
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 134, in connection
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     conn = self.get()
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 71, in get
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return self._connect()
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/root/idb-backend/idb/postgres_backend/gevent_helpers.py", line 55, in _connect
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     return psycopg2.connect(**self._connectargs)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]:     conn = _connect(dsn, connection_factory=connection_factory, async=async)
Nov 03 10:43:48 c18node4 idigbio-ingestion[29440]: psycopg2.OperationalError: could not translate host name "database_server" to address: Temporary failure in name resolution

```

**Comment by danstoner** [comment]
```

**Comment by danstoner** [comment]
Forthcoming code fix will:

```
# journalctl -f -u idigbio-ingestion-mediaing-get-media.service
...
Dec 12 13:06:44 c18node4 systemd[1]: idigbio-ingestion-mediaing-get-media.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 13:06:44 c18node4 systemd[1]: idigbio-ingestion-mediaing-get-media.service: Unit entered failed state.
Dec 12 13:06:44 c18node4 systemd[1]: idigbio-ingestion-mediaing-get-media.service: Failed with result 'exit-code'.

# systemctl --failed
  UNIT                                         LOAD   ACTIVE SUB    DESCRIPTION
● idigbio-ingestion-mediaing-get-media.service loaded failed failed iDigBio mediaing fetcher

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```
