### ISSUE TITLE
incremental indexer fatal crash

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#9]
```
Sleeping for 120 seconds
Starting Incremental Run at 2016-04-12T17:07:56.312174
Indexing publishers after 2016-03-24T16:25:51
publishers 0.0 0:00:00.011891 0.0
Indexing recordsets after 2016-04-12T16:21:05
recordsets 0.0 0:03:46.840475 0.0
Indexing mediarecords after 2016-04-12T16:49:18
mediarecords 10000.0 0:00:16.437926 608.348660678
Traceback (most recent call last):
  File "index_from_postgres.py", line 431, in <module>
    main()
  File "index_from_postgres.py", line 406, in main
    continuous_incremental(ei, rc)
  File "index_from_postgres.py", line 350, in continuous_incremental
    incremental(ei, rc, no_index=no_index)
  File "index_from_postgres.py", line 304, in incremental
    consume(ei, rc, type_yield_modified, no_index=no_index)
  File "index_from_postgres.py", line 341, in consume
    for ok, item in ei.bulk_index(p.imap(index_func, iter_func(ei, rc, typ, yield_record=True))):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: (u'56 document(s) failed to index.', [{u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'ff456e3a-aff2-4e63-bae3-216716e2729a'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'c11d8981-35b1-498f-ab6d-ee81c2df04f5'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'0c6cf001-c9b9-4b5b-b0a5-7231e712b253'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'c164fad0-cc36-4694-a3ab-efdf90232e07'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'68d7df4b-eeda-4e04-a755-62469a061e08'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'fa26a57b-172e-447e-8adf-80ad9a4f893f'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'28734ccf-9587-4399-b198-74022a9f9861'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'a53cd918-7a45-42dc-8e38-bf3982c0e0dc'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'017afba0-00f2-4cfd-985e-c236f61bad20'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'51311e50-49f1-46d8-ba78-1606c1f6fc97'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'8b06719c-8b89-40ea-a4ed-b74b5415a5bd'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'9fc908c6-b6d1-4e37-af92-20b580bbc7ab'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'30b74608-a4c2-44de-9d21-0fed9b9eb3e8'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'9f6dcd0c-035d-4f75-96c0-bc1fd2f39b00'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'67f828bc-a8d7-4b7c-9bf4-3b26fa60ea6b'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'f1098b59-cef6-404f-aae1-8a852bcc8632'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'92bfc8e3-6cd1-4442-a927-ef79971ca2e8'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'ffe0d94f-488d-4896-8d54-89e7253d0cf5'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'f70af180-9ba5-4a54-b4a6-4f9213bdc1f8'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'76c3a51f-6fea-4d3b-b5f0-c23786388ce3'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'aecf32fa-4d2e-40dd-8012-91f30be40649'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'b3ec4a0a-da4f-4b98-8d9a-0adf4760b700'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'950aebf4-2bb7-4c64-9a88-49e3e505df46'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'165a
root@c18node4:~/idb-backend/idb#
```

**Comment by danstoner** [comment]
Full indexer check `-k` completed successfully.

Running incremental again for next ingestion to see if we get a repeat event.

**Comment by danstoner** [comment]
Incremental indexer crashed again.

```
...
mediarecords 20000.0 0:00:38.612641 517.964886953
mediarecords 22043.0 0:00:47.703845 462.079959349
Traceback (most recent call last):
  File "index_from_postgres.py", line 431, in <module>
    main()
  File "index_from_postgres.py", line 406, in main
    continuous_incremental(ei, rc)
  File "index_from_postgres.py", line 350, in continuous_incremental
    incremental(ei, rc, no_index=no_index)
  File "index_from_postgres.py", line 304, in incremental
    consume(ei, rc, type_yield_modified, no_index=no_index)
  File "index_from_postgres.py", line 341, in consume
    for ok, item in ei.bulk_index(p.imap(index_func, iter_func(ei, rc, typ, yield_record=True))):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: (u'1197 document(s) failed to index.', [{u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'9cfae3e4-c777-42f1-9f2d-72696e641170'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'dd1022d0-aadf-461b-ae77-e86e761fe30f'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'67feae96-82ee-4399-a6f2-4d51b715d005'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'93a50aab-17c0-4032-b1b4-fbf1d7234208'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'2bfaedaa-a982-49bc-a6d5-95221ee850af'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'2f1263e9-7f60-4a05-863a-5b7e374db08e'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'6a6d5ebb-3685-45fc-ad4d-ce4b6b4e7492'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'314dfb2a-7ee0-46ad-9a87-394a0577b20b'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'3ea45875-0eb6-420c-8700-823e18a88be1'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'd4a9aef3-96db-4195-b65c-cb924f092487'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'b97aa961-7541-459b-b8d6-583919785e64'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'40524af5-5a1e-4437-bac6-ca67e51ccf84'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'979ecc2d-58ba-4aa0-bd25-4a9f9a290654'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'61d3f2f0-66b6-4b8c-b428-7cfda8d2155b'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'a8a42ac0-397a-4101-99f4-720aa4bf4d43'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'f2817323-1844-4078-8d36-0154101f5804'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'99881450-d097-4bec-a49c-d2bd8a5abbcd'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'fbb33caa-61a9-43a8-85e9-066c68f84bdb'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'c8c06b94-09c8-41a9-beea-afec63ff3ce4'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'7be9353a-acf3-4786-91cf-8e3e828ed75f'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'4e1634eb-bf0e-45ec-b62f-cf4f00a2b671'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'635c4785-61d5-490b-8f50-6466a042ab70'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'c0375a73-d8f2-4ea3-98ef-9a079a09f396'}}, {u'delete': {u'status': 404, u'_type': u'mediarecords', u'_index': u'idigbio-2.9.2', u'_version': 1, u'found': False, u'_id': u'29
```

**Comment by UnwashedMeme** [comment]
I think this is a 404 error that's from referencing the 2.9.2 index when we are now using 2.9.3; I think we fixed this in local config file while working on one of the others.
