### ISSUE TITLE
py.test Segmentation Fault in test_derivatives

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#92]
This occurs on a developer laptop:

```
py.test -v tests/idigbio_ingestion/mediaing/test_derivatives.py
======================================================================================== test session starts =========================================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.11, py-1.8.2, pluggy-0.13.1 -- /home/dan/git/IDIGBIO/idb-backend/.venv/bin/python2.7
cachedir: .pytest_cache
rootdir: /home/dan/git/IDIGBIO/idb-backend, inifile: setup.cfg
plugins: mock-1.13.0, cov-2.10.0, celery-4.2.2, flask-0.15.1
collected 10 items                                                                                                                                                                                   

tests/idigbio_ingestion/mediaing/test_derivatives.py::test_get_keys PASSED                                                                                                                     [ 10%]
tests/idigbio_ingestion/mediaing/test_derivatives.py::test_img_fetch[True] PASSED                                                                                                              [ 20%]
tests/idigbio_ingestion/mediaing/test_derivatives.py::test_img_fetch[False] PASSED                                                                                                             [ 30%]
tests/idigbio_ingestion/mediaing/test_derivatives.py::test_bad_key_bucket PASSED                                                                                                               [ 40%]
tests/idigbio_ingestion/mediaing/test_derivatives.py::test_resize[True] Segmentation fault (core dumped)
```

The test runs find on the workflow node.

Workaround in the meantime is to disable the affected tests or set of tests.

```
py.test -v tests/idigbio_ingestion/mediaing/test_derivatives.py --deselect=tests/idigbio_ingestion/mediaing/test_derivatives.py::test_resize --deselect=tests/idigbio_ingestion/mediaing/test_derivatives.py::test_generate_all_nonempty
```

**Comment by danstoner** [comment]
I'm guessing Pillow-SIMD is implicated here, and maybe has to do with missing instructions on the laptop cpu.  Guesses only at this point.

laptop:
```
$ cat /proc/cpuinfo
...
model name	: Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz
...
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
...
```

**Comment by danstoner** [comment]
The laptop includes `avx2` whereas the workflow node does not, it only has `avx`.

> SIMD stands for "single instruction, multiple data" and its essence is in performing the same operation on multiple data points simultaneously by using multiple processing elements. Common CPU SIMD instruction sets are MMX, SSE-SSE4, AVX, AVX2, AVX512, NEON.
>
> Currently, Pillow-SIMD can be compiled with SSE4 (default) or AVX2 support.

From: https://github.com/uploadcare/pillow-simd

**Comment by danstoner** [comment]
Segmentation fault is occurring in this call:

```python
GenerateResult(item.etag, list(items))
```

**Comment by danstoner** [comment]
Workflow node can run the derivatives tests successfully.  Workflow using older python and pytest but newer Pillow-SIMD library `Pillow_SIMD-5.1.1`.  Laptop is using `Pillow_SIMD-4.3.0`.

**Comment by danstoner** [comment]
Version of Pillow_SIMD does not seem to affect the behavior.  `Pillow_SIMD-5.1.1.post0` on laptop still segfaults.  `Pillow-SIMD-4.3.0.post0` on alternate workflow node (c18node15) has no problem.

Next would be to dig into other C modules being used by `GenerateResult`. 

The two main reasons for python to segfault are 1. out of memory  2. error in c lib

**Comment by danstoner** [comment]
I have tested on a few more computers.  `tests/idigbio_ingestion/mediaing/test_derivatives.py::test_resize` always triggers Segmentation fault on Ubuntu 18.04.  The workflow nodes that succeed are on Ubuntu 16.04.

**Comment by danstoner** [comment]
Here is the gdb backtrace:

```
gdb python
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run /home/dan/git/IDIGBIO/idb-backend/.venvSIMD/bin/py.test
Starting program: /home/dan/git/IDIGBIO/idb-backend/.venvSIMD/bin/python /home/dan/git/IDIGBIO/idb-backend/.venvSIMD/bin/py.test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.17, pytest-4.6.11, py-1.9.0, pluggy-0.13.1
rootdir: /home/dan/git/IDIGBIO/idb-backend, inifile: setup.cfg
plugins: mock-1.13.0, cov-2.10.0, celery-4.2.2, flask-0.15.1
collecting ... [New Thread 0x7fffe9e3b700 (LWP 24323)]
[New Thread 0x7fffe963a700 (LWP 24324)]
[New Thread 0x7fffe6e39700 (LWP 24325)]
collecting 23 items                                                                                                                              [Thread 0x7fffe6e39700 (LWP 24325) exited]
[Thread 0x7fffe963a700 (LWP 24324) exited]
[Thread 0x7fffe9e3b700 (LWP 24323) exited]
collected 225 items                                                                                                                              

tests/test_data_exists.py .......                                                                                                          [  3%]
tests/idb/test_cli.py ...                                                                                                                  [  4%]
tests/idb/test_data_api_basic.py ssss                                                                                                      [  6%]
tests/idb/test_data_api_downloads.py sssssssss                                                                                             [ 10%]
tests/idb/test_data_api_lookups.py sssss                                                                                                   [ 12%]
tests/idb/test_data_api_media.py ssssssssssssssssssssssssss                                                                                [ 24%]
tests/idb/test_helpers_conversions.py ................................                                                                     [ 38%]
tests/idb/test_helpers_idb_flask_authn.py s                                                                                                [ 38%]
tests/idb/test_helpers_media_validation.py ........                                                                                        [ 42%]
tests/idb/test_helpers_memoize.py .......                                                                                                  [ 45%]
tests/idb/test_helpers_query_shim.py ...........................                                                                           [ 57%]
tests/idb/test_helpers_storage.py ...                                                                                                      [ 58%]
tests/idb/test_idbmodel.py s                                                                                                               [ 59%]
tests/idb/test_indexer_indexing.py .                                                                                                       [ 59%]
tests/idb/test_logging.py .......                                                                                                          [ 62%]
tests/idb/test_media_object.py ....sssssss                                                                                                 [ 67%]
tests/idb/test_pg_pool.py sssssssssssssssssssssssssssss                                                                                    [ 80%]
tests/idigbio_ingestion/test_db_check.py .                                                                                                 [ 80%]
tests/idigbio_ingestion/lib/test_eml.py ...................                                                                                [ 89%]
tests/idigbio_ingestion/mediaing/test_derivatives.py ....
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffdbbbe154 in ImagingResampleHorizontalConvolution8u4x (lineOut0=0x5555590782a0, lineOut1=0x5555590786b0, lineOut2=0x555559078ac0, 
    lineOut3=0x555559078ed0, lineIn0=0x555559213f00, lineIn1=0x555559215d00, lineIn2=0x555559217b00, lineIn3=0x555559219900, xsize=260, 
    xbounds=0x555559052ce0, kk=0x555559063c60, kmax=17, coefs_precision=17) at src/libImaging/ResampleSIMDHorizontalConv.c:185
185	src/libImaging/ResampleSIMDHorizontalConv.c: No such file or directory.
(gdb) backtrace
#0  0x00007fffdbbbe154 in ImagingResampleHorizontalConvolution8u4x (lineOut0=0x5555590782a0, lineOut1=0x5555590786b0, lineOut2=0x555559078ac0, 
    lineOut3=0x555559078ed0, lineIn0=0x555559213f00, lineIn1=0x555559215d00, lineIn2=0x555559217b00, lineIn3=0x555559219900, xsize=260, 
    xbounds=0x555559052ce0, kk=0x555559063c60, kmax=17, coefs_precision=17) at src/libImaging/ResampleSIMDHorizontalConv.c:185
#1  0x00007fffdbbc2fe8 in ImagingResampleHorizontal_8bpc (imOut=0x555556a4eea0, imIn=0x555559004120, offset=0, ksize=17, bounds=0x555559052ce0, 
    prekk=0x555559063c60) at src/libImaging/Resample.c:288
#2  0x00007fffdbbc3d4c in ImagingResampleInner (imIn=0x555559004120, xsize=260, ysize=195, filterp=0x7fffdbe21d10 <BILINEAR>, 
    box=0x7fffffff84b0, ResampleHorizontal=0x7fffdbbc2d0e <ImagingResampleHorizontal_8bpc>, 
    ResampleVertical=0x7fffdbbc3098 <ImagingResampleVertical_8bpc>) at src/libImaging/Resample.c:559
#3  0x00007fffdbbc3acb in ImagingResample (imIn=0x555559004120, xsize=260, ysize=195, filter=2, box=0x7fffffff84b0)
    at src/libImaging/Resample.c:507
#4  0x00007fffdbbb066a in _resize (self=0x7fffdac5a2f0, args=0x7fffdac5ca50) at src/_imaging.c:1549
#5  0x0000555555648bba in PyEval_EvalFrameEx ()
#6  0x00005555556462aa in PyEval_EvalCodeEx ()
#7  0x000055555564ddce in PyEval_EvalFrameEx ()
#8  0x00005555556462aa in PyEval_EvalCodeEx ()
#9  0x000055555564e39e in PyEval_EvalFrameEx ()
#10 0x00005555556462aa in PyEval_EvalCodeEx ()
#11 0x00005555556621cc in ?? ()
#12 0x0000555555631e6e in PyObject_Call ()
#13 0x000055555564b092 in PyEval_EvalFrameEx ()
#14 0x00005555556462aa in PyEval_EvalCodeEx ()
#15 0x0000555555661f29 in ?? ()
#16 0x0000555555631e6e in PyObject_Call ()
#17 0x000055555564b092 in PyEval_EvalFrameEx ()
#18 0x00005555556462aa in PyEval_EvalCodeEx ()
#19 0x000055555564ddce in PyEval_EvalFrameEx ()
#20 0x00005555556462aa in PyEval_EvalCodeEx ()
#21 0x000055555564e39e in PyEval_EvalFrameEx ()
#22 0x000055555564d926 in PyEval_EvalFrameEx ()
#23 0x00005555556462aa in PyEval_EvalCodeEx ()
#24 0x00005555556621cc in ?? ()
#25 0x000055555567a70e in ?? ()
#26 0x0000555555631e6e in PyObject_Call ()
#27 0x00005555556d7be3 in ?? ()
#28 0x000055555564db20 in PyEval_EvalFrameEx ()
#29 0x00005555556462aa in PyEval_EvalCodeEx ()
#30 0x000055555564e39e in PyEval_EvalFrameEx ()
#31 0x00005555556462aa in PyEval_EvalCodeEx ()
#32 0x0000555555661f29 in ?? ()
#33 0x0000555555631e6e in PyObject_Call ()
#34 0x000055555564b092 in PyEval_EvalFrameEx ()
#35 0x00005555556462aa in PyEval_EvalCodeEx ()
#36 0x000055555564ddce in PyEval_EvalFrameEx ()
#37 0x00005555556462aa in PyEval_EvalCodeEx ()
#38 0x000055555564e39e in PyEval_EvalFrameEx ()
#39 0x000055555564d926 in PyEval_EvalFrameEx ()
#40 0x00005555556462aa in PyEval_EvalCodeEx ()
#41 0x00005555556621cc in ?? ()
#42 0x000055555567a70e in ?? ()
#43 0x0000555555631e6e in PyObject_Call ()
#44 0x00005555556d7be3 in ?? ()
#45 0x0000555555631e6e in PyObject_Call ()
#46 0x000055555564b092 in PyEval_EvalFrameEx ()
#47 0x00005555556462aa in PyEval_EvalCodeEx ()
#48 0x000055555564e39e in PyEval_EvalFrameEx ()
#49 0x00005555556462aa in PyEval_EvalCodeEx ()
#50 0x000055555564ddce in PyEval_EvalFrameEx ()
```

**Comment by danstoner** [comment]
Same / similar issue?

https://github.com/uploadcare/pillow-simd/issues/59

**Comment by danstoner** [comment]
Supposedly fixed in a version of Pillow-SIMD that no longer supports python 2.x.

**Comment by roncanepa** [comment]
At this point, might be worth switching back to the original version of pillow until such time that the backend is fully 3.x-compatible.

**Comment by danstoner** [comment]
The existing (old) workflow nodes are on Python 2.7.12.  These are the ones crunching millions of images that would benefit from the Pillow-SIMD performance gain.

The issue mentioned https://github.com/iDigBio/idb-backend/issues/92#issuecomment-655163508 indicates the problem may have started with a later python.

We might be able to add a branch in setup.py to use Pillow-SIMD if on Python 2.7.12 but use regular Pillow everywhere else. Not sure about that, though.

**Comment by danstoner** [comment]
maybe like https://stackoverflow.com/questions/19672980/can-you-set-conditional-dependencies-for-python-2-and-3-in-setuptools
